# Generated by Django 4.2.18 on 2025-03-10 08:49

from django.db import migrations, models
import django.db.models.deletion
import eventApp.models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название мероприятия')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Слаг')),
                ('description', models.TextField(blank=True, verbose_name='Описание меропрития')),
                ('date_start', models.DateTimeField(verbose_name='Дата и время начала мероприятия')),
                ('date_end', models.DateTimeField(verbose_name='Дата и время конца мероприятия')),
                ('age_limit', models.PositiveIntegerField(default=0, verbose_name='Возрастное ограничение')),
                ('event_format', models.CharField(choices=[('Online', 'Онлайн'), ('Offline', 'Оффлайн')], max_length=7, verbose_name='Формат мероприятия')),
                ('registration_status', models.BooleanField(default=False, verbose_name='Статус регистрации для мероприятия')),
                ('participants_limit', models.PositiveIntegerField(default=1, verbose_name='Лимит участников')),
                ('available_places', models.PositiveIntegerField(default=1, verbose_name='Количество свободных мест')),
                ('location_offline', models.CharField(blank=True, max_length=300, null=True, verbose_name='Место проведения мероприятия оффлайн')),
                ('city', models.CharField(blank=True, max_length=300, null=True, verbose_name='Город, в котором проводится оффлайн мероприятия')),
                ('location_online', models.URLField(blank=True, max_length=300, null=True, verbose_name='Ссылка для проведения онлайн мероприятия')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус активности мероприятия')),
                ('main_photo', imagekit.models.fields.ProcessedImageField(blank=True, upload_to=eventApp.models.event_main_photo_path, verbose_name='Фото для обложки')),
                ('category', models.ManyToManyField(related_name='events', to='eventApp.category', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
        migrations.CreateModel(
            name='EventImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to=eventApp.models.event_additional_image_path, verbose_name='Картинки для мероприятия')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_images', to='eventApp.event', verbose_name='Мероприятие')),
            ],
            options={
                'verbose_name': 'Картинка для мероприятий',
                'verbose_name_plural': 'Картинки для мероприятий',
            },
        ),
    ]
