# Generated by Django 4.2.18 on 2025-02-12 11:18

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('format', models.CharField(choices=[('Online', 'Онлайн'), ('Offline', 'Оффлайн')], max_length=7)),
                ('registration_status', models.BooleanField(default=False)),
                ('participants_limit', models.PositiveIntegerField(default=1)),
                ('age_limit', models.PositiveIntegerField(default=0)),
                ('location', models.CharField(max_length=300)),
                ('main_photo', imagekit.models.fields.ProcessedImageField(upload_to='main_images/')),
                ('category', models.ManyToManyField(related_name='events', to='eventApp.category')),
            ],
        ),
        migrations.CreateModel(
            name='EventImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='images/')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_images', to='eventApp.event')),
            ],
        ),
    ]
