# Generated by Django 5.1.6 on 2025-03-03 11:15

import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EventImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('event_format', models.CharField(choices=[('Online', 'Онлайн'), ('Offline', 'Оффлайн')], max_length=7)),
                ('registration_status', models.BooleanField(default=False)),
                ('participants_limit', models.PositiveIntegerField(default=1)),
                ('available_places', models.PositiveIntegerField(default=0)),
                ('age_limit', models.PositiveIntegerField(default=0)),
                ('location_offline', models.CharField(blank=True, max_length=300, null=True)),
                ('city', models.CharField(blank=True, max_length=300, null=True)),
                ('location_online', models.URLField(blank=True, max_length=300, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('main_photo', imagekit.models.fields.ProcessedImageField(blank=True, upload_to='main_images/')),
                ('category', models.ManyToManyField(related_name='events', to='eventApp.category')),
            ],
        ),
    ]
