# Generated by Django 4.2.18 on 2025-02-12 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['title'], name='eventApp_ev_title_9c309c_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['date_start', 'date_end'], name='eventApp_ev_date_st_303bc3_idx'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(check=models.Q(('date_end__gt', models.F('date_start'))), name='check_data'),
        ),
    ]
