# Generated by Django 5.1.6 on 2025-03-03 11:15

import django.db.models.deletion
import eventApp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(default=eventApp.models.get_default_organizer, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventimages',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_images', to='eventApp.event'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['title'], name='eventApp_ev_title_9c309c_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['date_start', 'date_end'], name='eventApp_ev_date_st_303bc3_idx'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(check=models.Q(('date_end__gt', models.F('date_start'))), name='check_data'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('location_offline__isnull', True), ('location_online__isnull', False)), models.Q(('location_offline__isnull', False), ('location_online__isnull', True)), _connector='OR'), name='check_location'),
        ),
    ]
