# Generated by Django 5.1.6 on 2025-03-05 09:13

import django.db.models.deletion
import eventApp.models
import imagekit.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventApp', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Мероприятие', 'verbose_name_plural': 'Мероприятия'},
        ),
        migrations.AlterModelOptions(
            name='eventimages',
            options={'verbose_name': 'Картинка для мероприятий', 'verbose_name_plural': 'Картинки для мероприятий'},
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='event',
            name='age_limit',
            field=models.PositiveIntegerField(default=0, verbose_name='Возрастное мероприятие'),
        ),
        migrations.AlterField(
            model_name='event',
            name='available_places',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество свободных мест'),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.ManyToManyField(related_name='events', to='eventApp.category', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='event',
            name='city',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Город, в котором проводится оффлайн мероприятия'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_end',
            field=models.DateTimeField(verbose_name='Дата и время конца мероприятия'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_start',
            field=models.DateTimeField(verbose_name='Дата и время начала мероприятия'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание меропрития'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_format',
            field=models.CharField(choices=[('Online', 'Онлайн'), ('Offline', 'Оффлайн')], max_length=7, verbose_name='Формат мероприятия'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Статус активности мероприятия'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location_offline',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Место проведения мероприятия оффлайн'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location_online',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='Ссылка для проведения онлайн мероприятия'),
        ),
        migrations.AlterField(
            model_name='event',
            name='main_photo',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='main_images/', verbose_name='Фото для обложки'),
        ),
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(default=eventApp.models.get_default_organizer, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='events', to=settings.AUTH_USER_MODEL, verbose_name='Организатор мероприятия'),
        ),
        migrations.AlterField(
            model_name='event',
            name='participants_limit',
            field=models.PositiveIntegerField(default=1, verbose_name='Лимит участников'),
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_status',
            field=models.BooleanField(default=False, verbose_name='Статус регистрации для мероприятия'),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Название мероприятия'),
        ),
        migrations.AlterField(
            model_name='eventimages',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_images', to='eventApp.event', verbose_name='Мероприятие'),
        ),
        migrations.AlterField(
            model_name='eventimages',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='images/', verbose_name='Картинки для мероприятия'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['is_active'], name='eventApp_ev_is_acti_b8e9de_idx'),
        ),
    ]
