# Generated by Django 4.2.18 on 2025-02-13 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import eventApp.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventApp', '0003_alter_event_organizer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(default=eventApp.models.get_default_organizer, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='events', to=settings.AUTH_USER_MODEL),
        ),
    ]
