# Generated by Django 5.1.6 on 2025-03-05 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventApp', '0003_alter_event_options_alter_eventimages_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
