# Generated by Django 4.2.18 on 2025-02-17 07:07

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('eventApp', '0004_alter_event_organizer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='format',
            new_name='event_format',
        ),
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
        migrations.AddField(
            model_name='event',
            name='city',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='location_offline',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='location_online',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='main_photo',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='main_images/'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('location_offline__isnull', True), ('location_online__isnull', False)), models.Q(('location_offline__isnull', False), ('location_online__isnull', True)), _connector='OR'), name='check_location'),
        ),
    ]
