# Generated by Django 5.1.6 on 2025-03-05 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventApp', '0004_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='age_limit',
            field=models.PositiveIntegerField(default=0, verbose_name='Возрастное ограничение'),
        ),
        migrations.AlterField(
            model_name='event',
            name='available_places',
            field=models.PositiveIntegerField(default=models.PositiveIntegerField(default=1, verbose_name='Лимит участников'), verbose_name='Количество свободных мест'),
        ),
    ]
