# Generated by Django 5.1.6 on 2025-03-05 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventApp', '0005_alter_event_age_limit_alter_event_available_places'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='available_places',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество свободных мест'),
        ),
    ]
