# Generated by Django 4.2.18 on 2025-02-12 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('participantApp', '0001_initial'),
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participants',
            name='not_auth_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participants', to='userApp.notauthuser'),
        ),
        migrations.AddField(
            model_name='participants',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='participants',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('user__isnull', True), ('not_auth_user__isnull', False)), models.Q(('user__isnull', False), ('not_auth_user__isnull', True)), _connector='OR'), name='check_user_and_not_auth_user'),
        ),
    ]
