# Generated by Django 5.1.6 on 2025-03-03 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participantApp', '0001_initial'),
        ('userApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='participants',
            name='not_auth_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participants', to='userApp.notauthuser'),
        ),
        migrations.AddField(
            model_name='participants',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='participants',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('user__isnull', True), ('not_auth_user__isnull', False)), models.Q(('user__isnull', False), ('not_auth_user__isnull', True)), _connector='OR'), name='check_user_and_not_auth_user'),
        ),
        migrations.AddConstraint(
            model_name='participants',
            constraint=models.UniqueConstraint(fields=('user', 'event'), name='unique_user_on_vent'),
        ),
        migrations.AddConstraint(
            model_name='participants',
            constraint=models.UniqueConstraint(fields=('not_auth_user', 'event'), name='unique_not_auth_user_on_event'),
        ),
    ]
