# Generated by Django 5.1.6 on 2025-03-05 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventApp', '0003_alter_event_options_alter_eventimages_options_and_more'),
        ('participantApp', '0002_initial'),
        ('userApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participants',
            options={'verbose_name': 'Участник', 'verbose_name_plural': 'Участники'},
        ),
        migrations.AlterField(
            model_name='participants',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время регистрации на мероприятие'),
        ),
        migrations.AlterField(
            model_name='participants',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='eventApp.event', verbose_name='Мероприятие'),
        ),
        migrations.AlterField(
            model_name='participants',
            name='not_auth_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participants', to='userApp.notauthuser', verbose_name='Неавторизованный пользователь'),
        ),
        migrations.AlterField(
            model_name='participants',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participants', to=settings.AUTH_USER_MODEL, verbose_name='Авторизованный пользователь'),
        ),
    ]
