# Generated by Django 4.2.18 on 2025-03-10 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participantApp', '0001_initial'),
        ('eventApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, verbose_name='Текст отзыва')),
                ('rating', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Оценка мероприятия')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='eventApp.event', verbose_name='Мероприятие')),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='participantApp.participants', verbose_name='Участник')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'indexes': [models.Index(fields=['event'], name='reviewApp_r_event_i_6332b7_idx')],
            },
        ),
    ]
