# Generated by Django 4.2.18 on 2025-02-12 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventApp', '0001_initial'),
        ('participantApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('rating', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='eventApp.event')),
                ('participant', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='participantApp.participants')),
            ],
        ),
    ]
