# Generated by Django 4.2.18 on 2025-02-13 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('participantApp', '0003_alter_participants_user'),
        ('reviewApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='participant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='participantApp.participants'),
        ),
    ]
