# Generated by Django 5.1.6 on 2025-03-05 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventApp', '0003_alter_event_options_alter_eventimages_options_and_more'),
        ('participantApp', '0003_alter_participants_options_and_more'),
        ('reviewApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='eventApp.event', verbose_name='Мероприятие'),
        ),
        migrations.AlterField(
            model_name='review',
            name='participant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='participantApp.participants', verbose_name='Участник'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Оценка мероприятия'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(blank=True, verbose_name='Текст отзыва'),
        ),
    ]
