# Generated by Django 5.1.6 on 2025-03-05 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventApp', '0004_alter_category_options'),
        ('participantApp', '0003_alter_participants_options_and_more'),
        ('reviewApp', '0002_alter_review_event_alter_review_participant_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['event'], name='reviewApp_r_event_i_6332b7_idx'),
        ),
    ]
