# Generated by Django 4.2.18 on 2025-02-13 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0002_remove_customuser_date_birthday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='date_birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
