# Generated by Django 5.1.6 on 2025-03-05 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0002_alter_notauthuser_options_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Авторизованный пользователь', 'verbose_name_plural': 'Авторизованные пользователи'},
        ),
    ]
