# Generated by Django 5.1.6 on 2025-03-06 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0003_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='url_event',
            field=models.URLField(max_length=500, verbose_name='Ссылка'),
        ),
    ]
