# Generated by Django 5.1.6 on 2025-03-20 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventApp', '0003_alter_event_description'),
    ]

    operations = [
        # Установка расширения pg_trgm
        migrations.RunSQL(
            sql="CREATE EXTENSION IF NOT EXISTS pg_trgm;",
            reverse_sql="DROP EXTENSION IF EXISTS pg_trgm;",
        ),
        # Создание индекса для title с поддержкой триграмм
        migrations.RunSQL(
            sql='CREATE INDEX event_title_trgm_idx ON "eventApp_event" USING GIN (title gin_trgm_ops);',
            reverse_sql="DROP INDEX IF EXISTS event_title_trgm_idx;",
        ),
        # Создание индекса для description с поддержкой триграмм
        migrations.RunSQL(
            sql='CREATE INDEX event_description_trgm_idx ON "eventApp_event" USING GIN (description gin_trgm_ops);',
            reverse_sql="DROP INDEX IF EXISTS event_description_trgm_idx;",
        ),
        # Создание индекса для полнотекстового поиска
        migrations.RunSQL(
            sql='CREATE INDEX event_search_idx ON "eventApp_event" USING GIN (to_tsvector(\'russian\', title || \' \' || description));',
            reverse_sql="DROP INDEX IF EXISTS event_search_idx;",
        ),
    ]
